services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  B13\Otf\:
    resource: '../Classes/*'

  B13\Otf\Backend\Controller\OtfAjaxController:
    tags: ['backend.controller']

  B13\Otf\Evaluation\EvaluationRegistry:
    public: true
